### ISSUE TITLE
Installing with space in path

### ISSUE THREAD

**Issue by mischnic** [parro-it/libui-node#128]
In this issue (https://github.com/kusti8/proton-native/issues/182), a user had a project at `/Users/brihaspati.bharani/Desktop/My Projects/m-notes` (macOS):

```
15851 verbose stack Error: libui-node@0.2.1 install: libui-download && autogypi && npm run build
15851 verbose stack Exit status 1
15851 verbose stack at EventEmitter. (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
15851 verbose stack at emitTwo (events.js:135:13)
15851 verbose stack at EventEmitter.emit (events.js:224:7)
15851 verbose stack at ChildProcess. (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
15851 verbose stack at emitTwo (events.js:135:13)
15851 verbose stack at ChildProcess.emit (events.js:224:7)
15851 verbose stack at maybeClose (internal/child_process.js:943:16)
15851 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
15852 verbose pkgid libui-node@0.2.1
15853 verbose cwd /Users/brihaspati.bharani/Desktop/My Projects/m-notes
15854 verbose Darwin 17.7.0
15855 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
15856 verbose node v9.0.0
15857 verbose npm v6.4.1
15858 error code ELIFECYCLE
15859 error errno 1
15860 error libui-node@0.2.1 install: libui-download && autogypi && npm run build
15860 error Exit status 1
15861 error Failed at the libui-node@0.2.1 install script.
15861 error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by parro-it** [comment]
I don't know what can cause problems in path with spaces, I will check...

**Comment by mischnic** [comment]
I think it has something to do with node-gyp:

````
> libui-node@0.2.1 install /Users/niklas/Desktop/DEV-TEST/test folder/project/node_modules/libui-node
> libui-download && autogypi && npm run build

Downloaded zip: /Users/niklas/.libui/libui-shared-osx-x64-alpha3.5-master-008.tar.gz
Libui binaries extracted to: /Users/niklas/Desktop/DEV-TEST/test folder/project/node_modules/libui-node

> libui-node@0.2.1 build /Users/niklas/Desktop/DEV-TEST/test folder/project/node_modules/libui-node
> node-gyp configure build

make: Entering directory '/Users/niklas/Desktop/DEV-TEST/test folder/project/node_modules/libui-node/build'
  COPY Release/obj.target/nbind/geni/symbols.txt
  CXX(target) Release/obj.target/nbind/../nbind/src/common.o
clang: error: no such file or directory: 'folder/project/node_modules/libui-node/src/includes'
clang: error: no such file or directory: 'folder/project/node_modules/libui-node'
make: *** [nbind.target.mk:200: Release/obj.target/nbind/../nbind/src/common.o] Error 1
make: Leaving directory '/Users/niklas/Desktop/DEV-TEST/test folder/project/node_modules/libui-node/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.12.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/niklas/Desktop/DEV-TEST/test folder/project/node_modules/libui-node
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.1 build: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libui-node@0.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/niklas/Library/Caches/npm/_logs/2018-10-18T15_00_56_264Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.1 install: `libui-download && autogypi && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libui-node@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/niklas/Library/Caches/npm/_logs/2018-10-18T15_00_56_926Z-debug.log
```

**Comment by mischnic** [comment]
Well:

> Closing. It's been discussed in other issues and it's not going to change; gyp itself doesn't support blanks in paths.

And we had that before: https://github.com/albe-rosado/create-proton-app/issues/14

(https://github.com/nodejs/node-gyp/issues/65)

**Comment by parro-it** [comment]
Ah yes, I vaguely remember we had that discussion...

> But libui-napi binaries will solve this

True, I should speed up its release...
