### ISSUE TITLE
npm ERR! libui-node@0.2.1 build: `node-gyp configure build`

### ISSUE THREAD

**Issue by wolandec** [parro-it/libui-node#130]
git clone https://github.com/parro-it/libui-node.git
npm install

```
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.14.89-desktop-1.mga6
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/disp/ideaworkspace/libui-node
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.1 build: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libui-node@0.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/disp/.npm/_logs/2019-01-25T08_01_09_978Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.1 install: `libui-download && autogypi && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libui-node@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/disp/.npm/_logs/2019-01-25T08_01_10_033Z-debug.log
```

**Comment by parro-it** [comment]
Could you post the compelte log :

> npm ERR! A complete log of this run can be found in:
npm ERR!     /home/disp/.npm/_logs/2019-01-25T08_01_10_033Z-debug.log

**Comment by wolandec** [comment]
> Could you post the compelte log :
> 
> > npm ERR! A complete log of this run can be found in:
> > npm ERR!     /home/disp/.npm/_logs/2019-01-25T08_01_10_033Z-debug.log

Yes, sure!

[2019-01-25T08_01_10_033Z-debug.log](https://github.com/parro-it/libui-node/files/2795759/2019-01-25T08_01_10_033Z-debug.log)

**Comment by wolandec** [comment]
Fixed, using this command.
sudo apt install libgtk-3-dev
