### ISSUE TITLE
ERR!  libui-node@0.2.1 install: `libui-download && autogypi && npm run build`

### ISSUE THREAD

**Issue by Chivi19** [parro-it/libui-node#132]
I get this error while trying to install libui-node with create-proton-app, I tried installing it externally but it failed that too.
I have both gtk3+ installed and build-essential
Platform: Xubuntu,
[2019-02-09T14_07_45_513Z-debug.log](https://github.com/parro-it/libui-node/files/2847873/2019-02-09T14_07_45_513Z-debug.log)

**Comment by bartolomej** [comment]
`784 verbose stack Error: libui-node@0.2.1 install: `libui-download && autogypi && npm run build`
784 verbose stack spawn ENOENT
784 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
784 verbose stack     at ChildProcess.emit (events.js:189:13)
784 verbose stack     at maybeClose (internal/child_process.js:978:16)
784 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
785 verbose pkgid libui-node@0.2.1
786 verbose cwd /Users/bartolomejkozorog/WebstormProjects/first-app
787 verbose Darwin 18.2.0
788 verbose argv "/usr/local/Cellar/node/11.4.0/bin/node" "/usr/local/bin/npm" "i"
789 verbose node v11.4.0
790 verbose npm  v6.5.0
791 error file sh
792 error code ELIFECYCLE
793 error errno ENOENT
794 error syscall spawn
795 error libui-node@0.2.1 install: `libui-download && autogypi && npm run build`
795 error spawn ENOENT
796 error Failed at the libui-node@0.2.1 install script.
796 error This is probably not a problem with npm. There is likely additional logging output above.`

Same issue here

**Comment by initforthelutz** [comment]
Same issue on Windows 10. [2019-04-25T23_47_32_803Z-debug.log](https://github.com/parro-it/libui-node/files/3119217/2019-04-25T23_47_32_803Z-debug.log)

**Comment by Euheimr** [comment]
Same issue here on Win10:
[2019-07-24T16_22_23_912Z-debug.log](https://github.com/parro-it/libui-node/files/3427821/2019-07-24T16_22_23_912Z-debug.log)
Tried using both Visual Studio 2015 and 2017.
I've also tried reinstalling both npm and node-gyp.

**Comment by AlbyIanna** [comment]
Same issue here with Ubuntu 18.04, node v12.7.0, npm 6.10.0
[2019-07-28T21_49_51_620Z-debug.log](https://github.com/parro-it/libui-node/files/3439604/2019-07-28T21_49_51_620Z-debug.log)

I also tried completely uninstall node, npm, node-gyp and re-install them with nvm.

**Comment by apollolux** [comment]
I technically have the same issue, but I was also trying to install libui-node while behind a corporate firewall AND without admin privileges AND as a result having to use older node, v8.11.something, Windows 7, so I don't think my encounter with this issue quite applies but it's at least something to think about later. Works fine on my macOS High Sierra where I'm not behind a firewall and I have admin privileges, though.

**Comment by fieldse** [comment]
Directory permissions error?
I've noted that there's a directory permissions error in the console output (not in the logs):
```
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/libui-node/.libui'
```
Hope this is a helpful lead.

**Comment by ghost** [comment]
Same issue here on Manjaro Linux **5.2.11-1-MANJARO**.

**npm**: v6.11.2
**node**: v12.9.1
**node-gyp**: v5.0.2

[2019-09-29T00_13_03_537Z-debug.log](https://github.com/parro-it/libui-node/files/3666156/2019-09-29T00_13_03_537Z-debug.log)

I have **base-devel** loaded for compiling needs...

- autoconf
- automake
- binutils
- bison
- fakeroot
- file
- findutils
- flex
- gawk
- gcc
- gettext
- grep
- groff
- gzip
- libtool
- m4
- make
- pacman
- patch
- pkgconf
- sed
- sudo
- systemd
- texinfo
- util-linux
- which

...and **gtk3**. `extra/gtk3 1:3.24.10-1 [installed]`

I also tried installing libui-node globally with `sudo` and too received the same permissions error when attempting to `mkdir '/usr/local/lib/node_modules/libui-node/.libui'`.

**Comment by apollolux** [comment]
Extra data for me. Cannot install on Win10 1903 Node v12.13.0, seems to be nbind related.

Gives a huge amount of errors like `error C2661: 'v8::Value::BooleanValue': no overloaded function takes 0 arguments (compiling source file ..\node_modules\nbind\src\reflect
.cc) [C:\apps\node\v12.13.0\node_modules\libui-node\build\nbind.vcxproj]` like the version of nbind used is old or something.

Also gives Warning: `Missing input files: C:\apps\node\v12.13.0\node_modules\libui-node\build\Release\nbind.node` without even bothering to check for any already-installed nbind (I have latest nbind installed globally).

Please update all the dependencies this project uses, including nbind and the latest version of libui too, so that we may try to install this on newer Node versions, thanks!
