### ISSUE TITLE
Linux tarball ends in .gz but isn't actually GZipped

### ISSUE THREAD

**Issue by paulcbetts** [parro-it/libui-node#30]
```
npm install libui-node
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> libui-node@0.0.3 install /home/paul/code/tinyspeck/trickline/node_modules/libui-node
> libui-download ${npm_package_libui} && autogypi && npm run build

Downloaded zip: /home/paul/.libui/libui-shared-linux-x64-preres-alpha4.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: Command failed: tar -xzvf /home/paul/.libui/libui-shared-linux-x64-preres-alpha4.tar.gz
    at checkExecSyncError (child_process.js:486:13)
    at execSync (child_process.js:526:13)
    at /home/paul/code/tinyspeck/trickline/node_modules/libui-download/cli.js:8:3
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Linux 4.4.2-6ph
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "libui-node"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
```

```
tar -xvf libui-shared-linux-x64-preres-alpha4.tar.gz 
libui.so
libui.so.0
ui_darwin.h
ui.h
uitable.h
ui_unix.h
ui_windows.h
```

**Comment by parro-it** [comment]
Thank you @paulcbetts, I think I miss -z [here](https://github.com/parro-it/libui/blob/master/scripts/create-artifacts-shared.sh#L9).

It's strange because the decompression command on OSX it's working, and I've created the OSX binaries with the same tar command. 

I will fix this soon

**Comment by parro-it** [comment]
Anyway, I havn't yet tested the npm package with Linux by now. It should work, but I'm not sure. It could be really helpful if you can give it a shot. 
Once you manually decompress the libui tarball, you should run `npm run autogypi && npm run build` to build the native part.

**Comment by PaulBGD** [comment]
You need to update the version in the package.json to the latest, because the preres version is just a tarfile.
```
paul@paulpc:~/Documents/Coding/libui-test$ file ~/.libui/libui-shared-linux-x64-preres-alpha4.tar.gz 
/home/paul/.libui/libui-shared-linux-x64-preres-alpha4.tar.gz: POSIX tar archive (GNU)
```

**Comment by parro-it** [comment]
Thank you @PaulBGD, done. I just publish ver 0.0.4. 
Tarball seems ok now, but I cannot test it on Linux at the moment. 
Please confirm it's working

**Comment by PaulBGD** [comment]
This occurs both with checking out the npm branch and installing libui-node as an npm dependency:
```
> libui-node@0.0.4 install /home/paul/Documents/Coding/libui-node
> libui-download ${npm_package_libui} && autogypi && npm run build

Downloaded zip: /home/paul/.libui/libui-shared-linux-x64-pre.alpha.4.tar.gz
libui.so
libui.so.0
ui_darwin.h
ui.h
uitable.h
ui_unix.h
ui_windows.h
Libui binaries extracted to: /home/paul/Documents/Coding/libui-node

> libui-node@0.0.4 build /home/paul/Documents/Coding/libui-node
> node-gyp configure build

make: Entering directory '/home/paul/Documents/Coding/libui-node/build'
  CXX(target) Release/obj.target/nbind/src/Size.o
  CXX(target) Release/obj.target/nbind/src/Point.o
  CXX(target) Release/obj.target/nbind/src/Color.o
  CXX(target) Release/obj.target/nbind/src/UiColorButton.o
  CXX(target) Release/obj.target/nbind/src/UiDialogs.o
  CXX(target) Release/obj.target/nbind/src/UiMenu.o
  CXX(target) Release/obj.target/nbind/src/UiCombobox.o
  CXX(target) Release/obj.target/nbind/src/UiSlider.o
  CXX(target) Release/obj.target/nbind/src/UiSpinbox.o
  CXX(target) Release/obj.target/nbind/src/UiCheckbox.o
  CXX(target) Release/obj.target/nbind/src/UiWindow.o
  CXX(target) Release/obj.target/nbind/src/UiEntry.o
  CXX(target) Release/obj.target/nbind/src/UiMultilineEntry.o
  CXX(target) Release/obj.target/nbind/src/UiRadioButtons.o
  CXX(target) Release/obj.target/nbind/src/UiEditableCombobox.o
  CXX(target) Release/obj.target/nbind/src/UiGroup.o
  CXX(target) Release/obj.target/nbind/src/UiTab.o
  CXX(target) Release/obj.target/nbind/src/UiBox.o
  CXX(target) Release/obj.target/nbind/src/UiDateTimePicker.o
  CXX(target) Release/obj.target/nbind/src/UiSeparator.o
  CXX(target) Release/obj.target/nbind/src/UiProgressBar.o
  CXX(target) Release/obj.target/nbind/src/Ui.o
  CXX(target) Release/obj.target/nbind/src/UiControl.o
  CXX(target) Release/obj.target/nbind/src/UiLabel.o
  CXX(target) Release/obj.target/nbind/src/UiButton.o
  SOLINK_MODULE(target) Release/obj.target/nbind.node
/usr/bin/ld: cannot find ..: File format not recognized
collect2: error: ld returned 1 exit status
nbind.target.mk:153: recipe for target 'Release/obj.target/nbind.node' failed
make: *** [Release/obj.target/nbind.node] Error 1
make: Leaving directory '/home/paul/Documents/Coding/libui-node/build'
```

**Comment by parro-it** [comment]
:hurtrealbad: I hit the npm index.js bug. 0.0.4 is missing index.js, try 0.0.5 instead. But I doubt this could be related...

**Comment by PaulBGD** [comment]
Same issue.

**Comment by parro-it** [comment]
I think I found the problem, I forgot to change a path on linux part of binding.gyp.
Version 0.0.6 should be ok (I hope :smile: )

**Comment by PaulBGD** [comment]
It fails earlier
```
paul@paulpc:~/Documents/Coding/libui-node$ npm install

> libui-node@0.0.6 install /home/paul/Documents/Coding/libui-node
> libui-download ${npm_package_libui} && autogypi && npm run build

Downloaded zip: /home/paul/.libui/libui-shared-linux-x64-pre.alpha.4.tar.gz
libui.so
libui.so.0
ui_darwin.h
ui.h
uitable.h
ui_unix.h
ui_windows.h
Libui binaries extracted to: /home/paul/Documents/Coding/libui-node

> libui-node@0.0.6 build /home/paul/Documents/Coding/libui-node
> node-gyp configure build

make: Entering directory '/home/paul/Documents/Coding/libui-node/build'
  SOLINK_MODULE(target) Release/obj.target/nbind.node
/usr/bin/ld: cannot find /home/paul/Documents/Coding/libui-node: File format not recognized
```

**Comment by parro-it** [comment]
It seems is not compiling the sources and just skip to linking: if you just `git pull` my last changes, you have to delete `build` folder. I will check it later today...

**Comment by PaulBGD** [comment]
Yeah I'm removing the old folder, deleting .libui, and installing. Should be completely clean.

**Comment by parro-it** [comment]
Ops it's trying to link the folder! Please try 0.0.7

**Comment by PaulBGD** [comment]
Copying the examples/core-api.js file and using libui-node as a module works great. I think this can be closed.

**Comment by parro-it** [comment]
Thank you @PaulBGD for your help, and thank you @paulcbetts to report!
